### ISSUE TITLE
Implement "Image Tools" in IIIF component

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches-for-science-prj#10]
Should be implemented in side panel tab as part of the IIIF component (see: https://github.com/archesproject/arches-for-science-prj/blob/master/afs/media/js/views/components/iiif-viewer.js & https://github.com/archesproject/arches-for-science-prj/blob/master/afs/templates/views/components/iiif-viewer.htm).

See mockup for details: 
<img width="393" alt="Screen Shot 2020-01-22 at 10 55 42 AM" src="https://user-images.githubusercontent.com/1187406/72924667-2fd7ee80-3d06-11ea-8937-e918a2a35071.png">

We should aim to support all of the "tools" depicted in the mockup, assuming that they are reasonably achievable.

**Comment by dwuthrich** [comment]
meets requirements
