### ISSUE TITLE
IIIF Thumbnails missing in Annotation widget

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches-for-science-prj#103]
When using this manifest:
https://media.nga.gov/public/manifests/nga_highlights.json

the thumbnails do not appear, but the main image does and zooms as expected.

Not sure why the thumbnails would be missing, as the service block of the image for the IIIF Image API is there, and works as expected.

**Comment by dwuthrich** [comment]
@azaroth42 I tested this manifest locally and am seeing thumbnails as expected

**Comment by azaroth42** [comment]
I was getting this:

![Screen Shot 2020-04-08 at 7 16 50 AM](https://user-images.githubusercontent.com/871868/78809220-6f17f200-797b-11ea-8c80-b886f7d76113.png)

But it must have been fixed recently, as I just repulled and they're working:

![Screen Shot 2020-04-08 at 9 35 27 AM](https://user-images.githubusercontent.com/871868/78809815-4e03d100-797c-11ea-93da-22ade7313c2f.png)

Closing :)
