### ISSUE TITLE
Multiple observations created when moving through the upload dataset workflow

### ISSUE THREAD

**Issue by aarongundel** [archesproject/arches-for-science-prj#1034]
If you go through the upload dataset workflow - pass the step where the new observation is created, and then go back to that step again.  The "Save and Continue" button lights up (it shouldn't, since nothing has changed).  If you press that button to move forward, the workflow advances and a second observation is created.  The workflow should only create one observation per run.

**Comment by apeters** [comment]
I"m not able to replicate this.

**Comment by aarongundel** [comment]
@apeters after looking at this, you need to refresh the page to replicate.  I think there's something that isn't saved in the workflow state properly.  So create the observation, go forward, then go back and refresh the page.
