### ISSUE TITLE
Advanced search facets have duplicates

### ISSUE THREAD

**Issue by johnatawnclementawn** [archesproject/arches-for-science-prj#1039]
Version: 6.2.x

Some resource facets have seemingly duplicate search options that need disambiguation: 

Duplicates in Collection/Set Facet: Duration of Timespan

Duplicates in Digital Resources Facet: Name for Statement 

Duplicates in Group Facet: Duration of TimeSpan (Timespan), Name for Duration of TimeSpan (Timespan), Name for Statement (x3), Name for TimeSpan (Timespan)

Duplicates in Instrument Facet: Name for Statement

Duplicates in Modification Facet: Name for Statement

Duplicates in Person Facet: (Duration for TimeSpan / Duration of TimeSpan),  Name for Duration of TimeSpan, Name for Duration of TimeSpan of Data Assignment, Name for Statement, Name for Statement about Data Assignment

Duplicates in Physical Thing Facet: Duration of TimeSpan, Name for Statement, Name for TimeSpan

Duplicates in Textual Work Facet: Duration of TimeSpan, Name for Creation Event;     *** It looks like the first and third facet items may not be rendering correctly - "of Textual Work" and "Creation (partitioned)_part_time_duration_Name"

**Comment by njkim** [comment]
@johnatawnclementawn 
Many models in AfS are complicated so some facets may look like duplicates but they may be from the different nodes.
Could you check if they are in fact duplicates?

**Comment by johnatawnclementawn** [comment]
@njkim Ahh, you're right. To the untrained eye, this is really confusing - there aren't any hints to the user that those facets are referring to different nodes. Even to the trained eye, it is tedious to decipher the target node. I think we could add some disambiguation to help the users quickly identify the node.

**Comment by aarongundel** [comment]
Issue moved to [archesproject/arches #9052](https://github.com/archesproject/arches/issues/9052) via [**Zenhub**](https://www.zenhub.com/)
