### ISSUE TITLE
reCaptcha error prevents user from creating a new account

### ISSUE THREAD

**Issue by johnatawnclementawn** [archesproject/arches-for-science-prj#1040]
Version: 6.2.x via Docker

Describe the bug and how to reproduce it:
When attempting to create a new account at http://localhost:8001/auth/signup, I am unable to create a new account because the captcha window displays an error: ERROR for site owner: Invalid site key.
There are no errors present in the browser console.

![Screen Shot](https://user-images.githubusercontent.com/22161487/197289959-d3cc1651-7e23-4029-ab8a-27f2a2e8ed18.png)

**Comment by aarongundel** [comment]
Issue moved to [archesproject/arches #9050](https://github.com/archesproject/arches/issues/9050) via [**Zenhub**](https://www.zenhub.com/)
