### ISSUE TITLE
User data entry access to Workflows

### ISSUE THREAD

**Issue by annabelleee** [archesproject/arches-for-science-prj#1056]
In setting up access for user testing by the GCI Technical Studies Research (TSR) group, I found that granting Resource Reviewer and Resource Editor permissions were not enough to grant access to use Workflows. Currently, I've given everyone superuser status, but is there a particular permissions group that grants Workflows access for data entry without using any of the administrator groups (Application Administrator, System Administrator, Graph Editor, Crowdsource Editor, Mobile Project Editor, RDM Administrator)?

**Comment by njkim** [comment]
@annabelleee You can set the permission for individual workflows using Django admin (eg. localhost:8000/admin)
From the admin page,
1. click plugins under Models
2. click the workflow you want to edit the permission. (you probably have to start with workflow plugin itself)
3. click Object permissions at the upper right corner
4. add group eg. Resource Editor
5. click manage group
6. set the permission

**Comment by annabelleee** [comment]
This worked! Thanks @njkim!
