### ISSUE TITLE
Error navigating to subsequent pages for selecting multiple objects under "New project workflow/ Add Object"

### ISSUE THREAD

**Issue by dmaclennan4** [archesproject/arches-for-science-prj#1093]
<img width="794" alt="issue1" src="https://user-images.githubusercontent.com/120419245/214964775-adce0de0-f027-4e79-88e0-b24c2b8543ff.png">

-adding the objects to project was temporarily frozen, after several minutes it became active.

**Comment by aarongundel** [comment]
We tracked this down to being an issue related to the performance of a particular api endpoint.  That endpoint timed out through the ALB after 60 seconds.  We made progress in improving the performance of this endpoint so that it would not be subject to the ALB timeout.

**Comment by chiatt** [comment]
Although this is partially addressed by https://github.com/archesproject/arches/pull/9259, I'm going to close this ticket as it is largely addressed in #1112
