### ISSUE TITLE
summary tab within multi-object project is blank

### ISSUE THREAD

**Issue by dmaclennan4** [archesproject/arches-for-science-prj#1096]
<img width="794" alt="issue3" src="https://user-images.githubusercontent.com/120419245/214967647-9eda4b6d-34e0-4b17-a043-c731c954306e.PNG">

summary tab is not populated for a multi-object project (Glass Project), but is populated for a single object project (2018.40 Rubens)

**Comment by dmaclennan4** [comment]
Update - we made a "mini" test of 3 objects, and they populated in the summary tab

<img width="795" alt="issue3 1" src="https://user-images.githubusercontent.com/120419245/214968776-2b402ec2-4a71-4179-a037-721f1e22e430.PNG">

**Comment by chiatt** [comment]
Addressed in #1110
