### ISSUE TITLE
IIIF component: Ensure "gallery" works for manifests w/ many sequences & canvases

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches-for-science-prj#11]
in the IIIF component, we need to ensure that we have good wrapping & scrolling styles for the bottom gallery.  This is important for manifests w/ many sequences and canvases.

Ideally, canvases should be arranged horizontally, grouped by sequence with a header showing the sequence name.  The gallery element should be of a fixed height (when shown) and content should overflow horizontally with horizontal scrolling enabled.

It might also be nice to implement right and left scrolling arrow buttons on either side of the gallery.

Example manifests can be found here:
https://ronallo.com/iiif-workshop/presentation/example-manifests.html

**Comment by dwuthrich** [comment]
meets requirements
