### ISSUE TITLE
Create workflow step in proj reporting workflow to screenshot labeled iiif annotations

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-for-science-prj#1133]
Users will need to be able to see a map of sample locations/analysis areas in project reports. To support this we will need a workflow step that shows an annotation map with labeled annotations. To accommodate a large number of annotation labels, they should probably be numeric. If labels are numeric, the annotation map will need to be accompanied by a table listing the annotation number and the name of analysis area/sample location.

**Comment by chiatt** [comment]
Users will need to be able to see a map of sample locations/analysis areas in project reports. To support this we will need a workflow step that shows an annotation map with labeled annotations. To accommodate a large number of annotation labels, they should probably be numeric. If labels are numeric, the annotation map will need to be accompanied by a table listing the annotation number and the name of analysis area/sample location.

**Comment by aarongundel** [comment]
This is already done.
