### ISSUE TITLE
Sample Taking Workflow null name

### ISSUE THREAD

**Issue by aarongundel** [archesproject/arches-for-science-prj#1139]
There's an issue in the sample taking workflow.  If you create a new sample, after you've done so, click the external green "Save" button at the bottom.  The last sample in the list will have its name turn "null".   The real problem here is that after you save the sample, the save button is still green - it should be disabled.

**Comment by chiatt** [comment]
Dang - I thought @njkim had this resolved. https://github.com/archesproject/arches-for-science-prj/pull/1131
