### ISSUE TITLE
Error in last step of New Project Workflow

### ISSUE THREAD

**Issue by ryan86** [archesproject/arches-for-science-prj#1169]
![Image](https://user-images.githubusercontent.com/3038476/239653098-d18425af-2b89-4ac0-84d8-da6e9dfa90bc.png)

**Comment by ryan86** [comment]
1.) Create a new phys thing with just a name
2.) Go through the New Project workflow and add just that one thing in the second to the last step
3.) When you save, you should get the error

**Comment by chiatt** [comment]
This seems to be resolved in the latest
