### ISSUE TITLE
Enable Arches to upload images to a directory available to a iiif server

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-for-science-prj#122]
@chiatt commented on [Wed Apr 29 2020](https://github.com/archesproject/arches/issues/6141)

Arches should be able to upload images to a dedicated directory that is available to a Cantaloupe server.

On upload a manifest record should be generated with at least a label - provided by the descriptor function, and the dimensions of the image.

**Comment by robgaston** [comment]
@whatisgalen are there instructions on how to test/QA this?

**Comment by chiatt** [comment]
Works as expected
