### ISSUE TITLE
Allow Project to Save without Activity Type in New Project Workflow

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-for-science-prj#1234]
First step in new project workflow fails if user does not select a Project Activity Type.  This is not a required node, so the project should save without error if the user does not add a type.

**Comment by jacobtylerwalls** [comment]
@chiatt The `type` node is actually [required](http://127.0.0.1:8000/graph_designer/0b9235d9-ca85-11e9-9fa2-a4d18cec433a). Should we add client-side validation for this or update the node to make it not required?

**Comment by chiatt** [comment]
Hmm... It makes me wonder if we are labeling the input incorrectly or if we are using the wrong Node. There is a Project Activity Type card that is not required, but has very different options.

![image](https://github.com/archesproject/arches-for-science-prj/assets/1877663/e3dbd051-d265-4dd2-806a-5dce6202d983)

The card that we seem to be using is Scale of Project:
![image](https://github.com/archesproject/arches-for-science-prj/assets/1877663/8fa221b3-4aba-4cee-9714-7a1466881fb9)

My guess is this is probably a labeling issue and that we have the right node. @annabelleee or @Habennin, could you confirm?

**Comment by njkim** [comment]
I believe, the choice of the node was the result of this.
https://github.com/archesproject/arches-for-science-prj/issues/979

**Comment by chiatt** [comment]
Then it seems like the label should change to reflect the change in node and match the card label in the resource editor. Otherwise, it could reemerge as a source of confusion.

**Comment by jacobtylerwalls** [comment]
Fixed in #1262
