### ISSUE TITLE
Each step of New Project Workflow has its own state of "Show step information" toggle

### ISSUE THREAD

**Issue by jacobtylerwalls** [archesproject/arches-for-science-prj#1240]
### Description ###
When toggled on, the state of the "show step information" toggle in the bottom bar of the New Project Workflow persists ~through steps 1-4, but when reaching Step 5, the toggle reverts to off.~ for each step independently.

### Version ###
arches 7.5 dev
afs 1.0 dev

**Comment by njkim** [comment]
@jacobtylerwalls I believe the intended behavior is here that each step can be controlled persistently but independently,
ie, the step info can be turned off even if all other steps are still showing the info, but next time the user use the same step again the info of that step's should stay turned off.
It looks like it follows the intended pattern but let me know if not.

**Comment by jacobtylerwalls** [comment]
Thanks @njkim I see now it's the original design to have an independent toggle for each page. I updated the issue title. @chiatt is going to mull it over in case we want to change the design, I think.

**Comment by chiatt** [comment]
I think we can keep the current design in 1.1, but I we should reconsider how we handle workflow help in the next version.
