### ISSUE TITLE
500 error in upload of image for new IIIF service

### ISSUE THREAD

**Issue by ekansa** [archesproject/arches-for-science-prj#1244]
In using this test deployment (https://vgm.fargeo.com/), I'm running into a 500 error when I attempt to upload a large (286 MB) TIF image to create a new IIIF service.

Attached is a screenshot of the 500 error.
![afs-iiif-upload-500-error](https://github.com/archesproject/arches-for-science-prj/assets/1286742/b6a6bd31-5b6f-47c1-8003-9dd0649723e2)

**Comment by chiatt** [comment]
Hey @ekansa, where are you storing your files? S3?

**Comment by ekansa** [comment]
Upload from my local machine. So not cloud storage.

**Comment by chiatt** [comment]
Hey @ekansa, I think the solution here is to use TIFFs with pyramids so I'm going close this issue.
