### ISSUE TITLE
Sample shape disappears if edited after initially created

### ISSUE THREAD

**Issue by jacobtylerwalls** [archesproject/arches-for-science-prj#1249]
1. Sample Taking Workflow
2. Sample info step: draw a line, save
3. Edit the points of the same line
Result: line "vanishes". Refreshing the page will restore it.

**Comment by johnatawnclementawn** [comment]
Did some initial debugging a few weeks ago and hypothesized that the issue could be coming from [these lines](https://github.com/archesproject/arches-for-science-prj/blob/8fb4bf7f61361bdb0eda6f3d5141389395892047/afs/media/js/views/components/workflows/sample-taking-workflow/sample-taking-sample-location-step.js#L915C33-L917). Attempted to remove the conditional on 915/918, however this was not the smoking gun and this will need to be further debugged.  It appears that there is logic that should re-add the feature to the canvas, but that logic is not being fired after a save event.

**Comment by johnatawnclementawn** [comment]
Resolved in #1307
