### ISSUE TITLE
"X" on filter image box wraps over label

### ISSUE THREAD

**Issue by jacobtylerwalls** [archesproject/arches-for-science-prj#1250]
1. Sample taking workflow
2. Sample info step
3. Type into the "search images" box at bottom
4. Observe "X" wraps over label "Filter"

**Before**
<img width="254" alt="Screenshot 2023-08-07 at 10 16 27 AM" src="https://github.com/archesproject/arches-for-science-prj/assets/38668450/0a11ba33-b71f-4e59-bf1d-caa6d0f46440">

**After**
<img width="248" alt="Screenshot 2023-08-07 at 10 16 18 AM" src="https://github.com/archesproject/arches-for-science-prj/assets/38668450/25efb858-b989-4a03-8bb9-ee8a82e100a7">

**Comment by chiatt** [comment]
moved to 9890
