### ISSUE TITLE
Sample name isn't required despite UI label

### ISSUE THREAD

**Issue by jacobtylerwalls** [archesproject/arches-for-science-prj#1251]
In the Sample Taking workflow, entering a sample name is not required after drawing a line despite the boxed label "Required" (and its inclusion in the validation message when attempting to save before creating the shape).

**Comment by chiatt** [comment]
I think this would be addressed by resolving https://github.com/archesproject/arches/issues/9281

**Comment by chiatt** [comment]
Fixed in archesproject/arches#9281
