### ISSUE TITLE
Need user group permissioning for access to workflows (dev/1.0.x)

### ISSUE THREAD

**Issue by ekansa** [archesproject/arches-for-science-prj#1257]
To access the workflows, it seems like one needs to be a superuser AND member of all (or some?) of the Arches predefined groups. We should probably create a "Workflow Group" to grant access to certain users to access the workflows. 

(cc @annabelleee who may have more ideas)

**Comment by chiatt** [comment]
It's definitely a bit tucked away, but there is already a way to control access to workflows. Workflows are actually Arches plugins and the permission to each of them can be controlled in the admin page using Django guardian. This gives an admin control over which users or groups have access to which workflows.

For Arches for Science, access to all workflows is through the 'Workflows' plugin, so an admin could control access to just that plugin if they wanted to.

![image](https://github.com/archesproject/arches-for-science-prj/assets/1877663/42516506-9517-41ff-94d7-36720d550fe0)

**Comment by chiatt** [comment]
@ekansa & @annabelleee I'm going to close this for now given my solution above, but feel free to reopen if something simpler is needed.

**Comment by jacobtylerwalls** [comment]
@chiatt I'm finding it insufficient to just give my dev/dev user permission for the `Workflows` object; I'm finding it necessary to manually enable each workflow. (E.g. clicking on the XY Workflow redirects me to login.) Does that go against your understanding of the current state of things?

**Comment by chiatt** [comment]
Thanks @jacobtylerwalls - My thought was that if permissions to the Workflows plugin was restricted, then it wouldn't be available in the main navigation bar. This would then conceal the workflows from the user. That probably is not secure enough, because if a user were to guess the slug, they could enter that slug in the url and access the workflow. So to be completely sure that the user had no workflow access, your right, each workflow would need to have permissions assigned.

**Comment by jacobtylerwalls** [comment]
Good point, but I was envisioning something even simpler, which is when you want to grant access to all workflows. Currently granting access to the generic workflow is insufficient; you have to enable each one. (Or am I missing something?)

**Comment by chiatt** [comment]
@jacobtylerwalls Ah, got it. I was testing with a user that had access to the Plugin model so I didn't see that problem. It looks like plugin access is the needed permission to grant access to all workflows. Some edits made by workflows are non-provisional, so to use workflows a user needs to be a ResourceReviewer. Maybe we should just add view access to the plugin model to the ResourceReviewer group?
