### ISSUE TITLE
Fix object selector label and alert

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-for-science-prj#1259]
The project info step in the Upload XY step has 2 issues

First - the label needs to be changed to the following:

Select an Object from from your project
**Object must have at least one analysis area or sample location**

Second - the alert that shows up if a user picks an object without an analysis area should be aligned with the form
![image](https://github.com/archesproject/arches-for-science-prj/assets/1877663/5189add4-f6f5-4021-8ce8-304581e6d8c4)

**Comment by johnatawnclementawn** [comment]
Resolved in #1261
