### ISSUE TITLE
Notification circle appears above "Return to Workflow" in sample taking image step

### ISSUE THREAD

**Issue by jacobtylerwalls** [archesproject/arches-for-science-prj#1260]
1. With the site up, load a package (afs)
2. Let the notification circle appear
3. Navigate to sample taking workflow image step

![Screenshot 2023-08-09 at 9 53 48 AM](https://github.com/archesproject/arches-for-science-prj/assets/38668450/da0a5597-2f0e-470b-9997-cc061b957ece)

**Comment by johnatawnclementawn** [comment]
Moved to [9909](https://github.com/archesproject/arches/issues/9909)
