### ISSUE TITLE
Sample Taking WF - Sample Info step hangs after saving edits to existing sample

### ISSUE THREAD

**Issue by johnatawnclementawn** [archesproject/arches-for-science-prj#1265]
1. Sample taking workflow
2. Sample info step: draw a feature, save
3. Sample info step loads, edit feature that was just created & save
4. Loading screen will hang on `Saved.` - requires a refresh to return to Sample info step

**Comment by jacobtylerwalls** [comment]
Hey @njkim is this ready to close?
