### ISSUE TITLE
Handle missing required values using server response

### ISSUE THREAD

**Issue by jacobtylerwalls** [archesproject/arches-for-science-prj#1269]
> I see this follows the same pattern as the `Project Name` node, but we should actually handle for missing required values using the response from the server.  That way the error message will be properly localized. We can address this for both nodes in another PR. This fix prevents the step from breaking, though, so it's a good stop-gap.

_Originally posted by @chiatt in https://github.com/archesproject/arches-for-science-prj/pull/1262#discussion_r1291905713_

**Comment by chiatt** [comment]
Perhaps this can be addressed as part of #1503?
