### ISSUE TITLE
Create IIIF Editor component, implement as widget and card component

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches-for-science-prj#13]
We need to create a IIIF editor component viewmodel.  This viewmodel should be suitable for use as both a widget and a card component.  It should extend the existing IIIF viewer component viewmodel and template.

We should then implement this viewmodel as a IIIF widget and card component.

**Comment by dwuthrich** [comment]
meets requirements

**Comment by dwuthrich** [comment]
meets requirement
