### ISSUE TITLE
Update project collection workflow shows child physical things inconsistently

### ISSUE THREAD

**Issue by jacobtylerwalls** [archesproject/arches-for-science-prj#1305]
I'm not certain of the exact intended behavior, but something looks inconsistent in this workflow.

1. Add a phys thing to a project
2. Take a bunch of samples
3. Update project collection: compare number of physical things to physical things in sidebar, make changes, save, reopen

https://github.com/archesproject/arches-for-science/assets/38668450/9db77ce2-c8d6-4472-840e-29251c0c350f

**Comment by chiatt** [comment]
I don't think users should be allowed to save any samples to their project.

**Comment by jacobtylerwalls** [comment]
Sounds like we'll wait for more clarity on whether to continue showing samples in a project in this UI.

I looked at my original video, and I think the "57 Physical Things" is intentional; it looks like it's the number of unpaginated search results, at least until you interact with the search, at which point it becomes the number of items in the current search result page. So there might not be a bug to fix here after all.
