### ISSUE TITLE
Update Collection Workflow back from summary error

### ISSUE THREAD

**Issue by aarongundel** [archesproject/arches-for-science-prj#1314]
In the update project collection workflow, complete the workflow to the summary step.  Then go back one step.  The attached error happens.  

![Screenshot 2023-09-18 at 3 18 23 PM](https://github.com/archesproject/arches-for-science/assets/124614/0324156a-43ab-46be-9523-1470d4346ef0)

**Comment by jacobtylerwalls** [comment]
Regression in #1239

**Comment by jacobtylerwalls** [comment]
Fixed in #1319
