### ISSUE TITLE
Show Step Information can cause UX problems

### ISSUE THREAD

**Issue by aarongundel** [archesproject/arches-for-science-prj#1320]
The "Show Step Information" dialog can cause some UX problems.  Mostly, when it's turned on it can push critical information below the viewable area on the screen.  A user might not notice the save/cancel buttons when it's turned on.  When it's turned off, the normal 100% height of the workflow returns and buttons become visible again.  An example of this is in the File Interpretation step on the XY workflow.  When adding the interpretation and parameters, the save and cancel buttons get knocked below the visible area.  There are two options here.  

1. We try to fix each step to make sure it doesn't go below the viewable area. 
2. We can rethink how Step Information is displayed altogether.

**Comment by chiatt** [comment]
I spoke with @dwuthrich about this and he agreed that we can display the step information above the step content rather than pushing the step content down.

**Comment by chiatt** [comment]
Replaced by: archesproject/arches#10222
