### ISSUE TITLE
Sample shape disappears if edit state initialized and no edits made

### ISSUE THREAD

**Issue by johnatawnclementawn** [archesproject/arches-for-science-prj#1321]
Sample Taking & Analysis Area Workflows:
1. Sample info or Region Step, respectively: draw & save n>=2 features
2. Click to initiate edit state on one feature, but do not make any edits
3. Move focus to the other feature
       Result: first feature "vanishes". Refreshing the page will restore it.

https://github.com/archesproject/arches-for-science/assets/22161487/ad77c9a9-acac-4f5c-9886-d230e1397105

**Comment by jacobtylerwalls** [comment]
It's the same with analysis area, too? (#1249 only affected sample taking.)

**Comment by johnatawnclementawn** [comment]
> It's the same with analysis area, too? (#1249 only affected sample taking.)

Yes, this is correct

**Comment by jacobtylerwalls** [comment]
After creating the second feature, instead of initializing an "edit state" on the other one, you can get it to vanish by just clicking cancel. The approach I have fixes that, too.
