### ISSUE TITLE
Advancing to step 2 of New Project Workflow unlocks all subsequent steps

### ISSUE THREAD

**Issue by jacobtylerwalls** [archesproject/arches-for-science-prj#1331]
1. New Project workflow, observe subsequent steps are disabled
2. Advance to step 2. Don't fill out the required statement.

Result: subsequent steps are enabled.
![Screenshot 2023-10-02 at 6 44 29 PM](https://github.com/archesproject/arches-for-science/assets/38668450/80228ac3-9fed-43b0-9a3a-5c3ef69cc802)

Or, is it just the case that the statement is actually not required? It seems to allow advancing without validation.

Version:
dev/7.5.x
Reproduced at:
archesproject/arches@4a2db69423202662f1e0212cb69373e27064176a
archesproject/arches-for-science@461c9ff8e8bed7419f4198de9e724f3b97cc74e2

**Comment by njkim** [comment]
@jacobtylerwalls It may sound unintuitive but I think the statement text is required to create a statement "tile" but a statement tile itself may not be required for the workflow.
