### ISSUE TITLE
Upload X/Y data workflow fails when attempting to load .pdf, .doc, .xls files

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches-for-science-prj#1342]
Attempting to upload files in formats other than .txt or .bmp fails silently.  At a minimum, Arches should alert a user if an upload requests fails.  We should support upload of common formats such as .pdf, .docx, .xls as well as the proprietary files produced by laboratory instruments.  GCI has provided examples of proprietary binary files produced by their lab instruments

**Comment by jacobtylerwalls** [comment]
Fixed in #1362 or earlier
