### ISSUE TITLE
Analysis area annotations not deleted when deleting workflow

### ISSUE THREAD

**Issue by jacobtylerwalls** [archesproject/arches-for-science-prj#1346]
Analysis area workflow:
1. Draw an analysis area annotation.
2. Save.
3. Delete workflow.

Result: annotation persists.

**Comment by chiatt** [comment]
Does the tile that the annotation belongs to continue to exist?

**Comment by jacobtylerwalls** [comment]
Can't reproduce. (Maybe I was on a bugfix branch.)
