### ISSUE TITLE
Prior analysis area annotations are not locked

### ISSUE THREAD

**Issue by jacobtylerwalls** [archesproject/arches-for-science-prj#1350]
In the sample taking workflow, if you create a sample of a physical thing, and then restart another workflow to create another sample, the first sample is shown as locked.

By contrast, in the analysis area workflow, if you do that, you can manipulate/delete the existing analysis area (it's not locked).

Is this intentional?

Found while dev'ing #1321

**Comment by chiatt** [comment]
This is intentional because the sample is saved to a sampling activity that corresponds to that iteration of the workflow. For analysis areas don't have that relationship.
