### ISSUE TITLE
Completing a step after resolving a TileValidationError jumps over a step

### ISSUE THREAD

**Issue by jacobtylerwalls** [archesproject/arches-for-science-prj#1354]
New project workflow:
1. Fill out scope, leave name blank
2. Next
3. Fill out name
4. Next

Expected: navigated to step 2
Actual: navigated to step 3

https://github.com/archesproject/arches-for-science/assets/38668450/d6829dd0-7675-48f5-9d3c-2e31f7a331c5

**Comment by jacobtylerwalls** [comment]
Maybe related: #1269

**Comment by jacobtylerwalls** [comment]
Should also retest with 7.4 since there's a [fix](https://github.com/archesproject/arches/pull/9895) for validation that hasn't been forwardported yet. (Or, at least test with the fix cherry-picked.)

**Comment by jacobtylerwalls** [comment]
Underlying validation issue fixed in #1340 by preventing a trip to the server. The step jumping would likely happen again in the case of future backend errors, though. @chiatt is worth pursuing that or should we put that on hold?

**Comment by chiatt** [comment]
Yeah - I do think we should address that issue

**Comment by jacobtylerwalls** [comment]
Sounds good -- it's addressed for the project name step (only) in #1374.
