### ISSUE TITLE
Physical thing search results do not indicate if in collection

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-for-science-prj#1356]
In the 'Add Objects to Your Project' step of the 'Update Project Collection Workflow' if a user selects a physical thing to add to a collection, it gets listed on the right. However, there is no indication in the list on the left that it has been added. That means that somebody could remove an object from a project by accident if they did not see that it was already added on the right. 

If an object has already been added to the collection there should be a clear indication that it has already been added, or it should hidden entirely from the search results so that it can only be removed from the collection by clicking the remove button in the list on the right.
![image](https://github.com/archesproject/arches-for-science/assets/1877663/443974d6-d91c-4861-91b2-c0e286c5458f)

**Comment by jacobtylerwalls** [comment]
Hmm, I thought I remembered fixing this recently. I'll take a look.
