### ISSUE TITLE
Installation README Ambiguity (dev/1.1.x)

### ISSUE THREAD

**Issue by ekansa** [archesproject/arches-for-science-prj#1373]
In the installation README (https://github.com/archesproject/arches-for-science/blob/dev/1.1.x/README.md#2-project-configuration), there seems to be some ambiguity about the 'myappname' app added to the `INSTALLED_APPS` config in `settings.py`. 

Should this be removed or updated?

**Comment by ekansa** [comment]
The project settings.py that I created from dev/7.5.x doesn't have `RENDERERS` defined. Maybe we should add something like this?

```python
# A hack to see if this exists.
try:
    RENDERERS
except NameError:
    RENDERERS = []

RENDERERS += [
    {
        "name": "xy-reader",
        "title": "XY Data File Reader",
        "description": "Use for all instrument outputs with x-y data",
        "id": "e93b7b27-40d8-4141-996e-e59ff08742f3",
        "iconclass": "fa fa-bolt",
        "component": "views/components/cards/file-renderers/xy-reader",
        "ext": "txt",
        "type": "text/plain",
        "exclude": "",
    },
]

```

**Comment by ekansa** [comment]
Also an issue with the changes to urls.py:

```
from django.conf.urls import path, include
arches                | ImportError: cannot import name 'path' from 'django.conf.urls' (/root/.local/lib/python3.10/site-packages/django/conf/urls/__init__.py)
```

**Comment by ekansa** [comment]
Hmmm...

Maybe a Django version issue with this:
```
from django.conf.urls import path, include
ImportError: cannot import name 'path' from 'django.conf.urls' (/root/.local/lib/python3.10/site-packages/django/conf/urls/__init__.py)
```

Something like this work?

```python
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    re_path(r'^', include('arches.urls')),
    re_path(r"^", include("arches_for_science.urls")),
    path("reports/", include("arches_templating.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
```

**Comment by jacobtylerwalls** [comment]
Thanks, these are really helpful observations.

> The project settings.py that I created from dev/7.5.x doesn't have RENDERERS defined. 

Nice catch. `settings.RENDERERS` is defined in core arches and [documented](https://github.com/archesproject/arches-docs/blob/bd3d919661e2f210f755a500abfa9641ef4970d0/docs/developing/reference/import-export.txt#L170), so IMO it's safe to depend on, and we should just update the settings template and mention in the AFS readme that some projects may have been created without this setting. What do you think?

> Maybe a Django version issue with this:

Ah, thanks. Yeah, the arches app feature was developed in tandem with the django upgrade and we didn't account for that here. [DISCO is a good reference](https://github.com/archesproject/disco/blob/main/disco/urls.py), except here I'll probably suggest just sticking with `path()` since we don't need a regex.

> there seems to be some ambiguity about the 'myappname' app

Can you elaborate on what you found difficult to follow? I only see one reference to the myappname placeholder, and in your case it would be `afs_plocal`, so the README looks correct.

**Comment by ekansa** [comment]
Thanks!! @jacobtylerwalls  I'll to use your README update as a guide for my next attempts at deployment.

**Comment by ekansa** [comment]
@jacobtylerwalls I think I'm still missing something critical. When I run Webpack, I get 500 errors on the workflow related templates:

```
arches                | [23/Oct/2023 19:49:00] "GET /templates/views/components/workflows/project-report-workflow/download-project-files.htm HTTP/1.1" 500 94187
arches                | [23/Oct/2023 19:49:00] "GET /templates/views/components/workflows/chemical-analysis-workflow/ca-final-step.htm HTTP/1.1" 500 94127
arches                | [23/Oct/2023 19:49:00] "GET /templates/views/components/workflows/create-project-workflow/add-things-step.htm HTTP/1.1" 500 94117
arches                | [23/Oct/2023 19:49:00] "GET /templates/views/components/workflows/chemical-analysis-workflow/ca-upload-files-step.htm HTTP/1.1" 500 94197
arches                | [23/Oct/2023 19:49:00] "GET /templates/views/components/workflows/chemical-analysis-workflow/ca-instrument-info-step.htm HTTP/1.1" 500 94227
arches                | [23/Oct/2023 19:49:00] "GET /templates/views/components/workflows/project-report-workflow/project-report-select.htm HTTP/1.1" 500 94177
arches                | [23/Oct/2023 19:49:00] "GET /templates/views/components/workflows/project-report-workflow/add-annotations.htm HTTP/1.1" 500 94117
arches                | [23/Oct/2023 19:49:00] "GET /templates/views/components/workflows/project-collection-workflow/project-collection-final-step.htm HTTP/1.1" 500 94297
```

Also:
```
arches                 | No module named 'arches_for_science_package'
```

**Comment by ekansa** [comment]
Also, I'm puzzled about installation of cantaloupe? Shouldn't this be part of the README?

**Comment by jacobtylerwalls** [comment]
> arches                 | No module named 'arches_for_science_package'

Good catch, it should just be `arches_for_science`: see [396eacc](https://github.com/archesproject/arches-for-science/commit/396eacc7db586221d810ba0167ade50e76a99e20).

**Comment by jacobtylerwalls** [comment]
Added cantaloupe note in 4830b39e444452b04aa20030176a7db08e9c9c81.

**Comment by ekansa** [comment]
@jacobtylerwalls Thanks so much for the updates!

I'm still getting build errors in webpack. I'm missing a `FORMATS` attribute in settings (should this be added to the README?) and the templates are giving me some issues. See below. The exact settings I'm using are here:

https://github.com/opencontext/arches-via-docker/blob/local-afs-dev-1-1-x/arches/settings.py


```
arches                 | [24/Oct/2023 18:40:04] "GET /templates/views/components/cards/map.htm HTTP/1.1" 500 94811
arches                 | [24/Oct/2023 18:40:04] "GET /templates/views/components/cards/file-viewer.htm HTTP/1.1" 500 94891
arches                 | 'Settings' object has no attribute 'FORMATS'
arches                 | Internal Server Error: /templates/views/components/map.htm
arches                 | Traceback (most recent call last):
arches                 |   File "/root/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
arches                 |     response = get_response(request)
arches                 |   File "/root/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 204, in _get_response
arches                 |     self.check_response(response, callback)
arches                 |   File "/root/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 332, in check_response
arches                 |     raise ValueError(
arches                 | ValueError: The view arches.app.views.main.templates didn't return an HttpResponse object. It returned None instead.
```

**Comment by jacobtylerwalls** [comment]
Good catch, looks a docs regression in d82bb80. I'll open a PR.
