### ISSUE TITLE
Prevent question mark from appearing in resource instance dropdown

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-for-science-prj#1391]
Physical things are represented with a ? in the first step of the chemical analysis workflow. In the project report workflow, the icon is shown, and in upload xy, it's blank. It would be good if the icon was shown, but if that's difficult to do nothing should be shown. What's important is that it isn't a question mark. 

![image](https://github.com/archesproject/arches/assets/1877663/2b161c9b-7f45-478c-af9f-c58e38a2be00)
![image](https://github.com/archesproject/arches-for-science/assets/1877663/fbfc1edd-1593-4305-b84b-57dfc06dac79)
![image](https://github.com/archesproject/arches-for-science/assets/1877663/6a014eb5-1c9a-4679-a9d3-1e8ee1d89fae)

**Comment by jacobtylerwalls** [comment]
Solution might be the same as 81f5d5f0519324b36fe27fc7d1b64f129755089f
