### ISSUE TITLE
User gets no error when trying to save a sample without a required node

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-for-science-prj#1419]
When saving a sample, a user must provide a name, otherwise the save will fail. When it does, the user should get an alert notifying them that they need to provide a sample name. 

![image](https://github.com/archesproject/arches-for-science/assets/1877663/476a7c05-c17b-44e7-8b89-0db558ca93ab)

**Comment by jacobtylerwalls** [comment]
Fixed in #1427
