### ISSUE TITLE
Fix size of the right panel in the multi tile step

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-for-science-prj#143]
The panel with the existing tiles on the right of the multi tile step is only 217 px wide.  It should be 500 px wide for the content to display properly.

![image.png](https://images.zenhubusercontent.com/57d0a2a4e40e5714b16e73d7/d77415cc-70e7-4e47-9e1e-feddeab1f509)

**Comment by dwuthrich** [comment]
meets requirements
