### ISSUE TITLE
Search in update project workflows does not work as expected

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-for-science-prj#1435]
Users should be able to search on the name, author, or other identifier of a physical thing. A term search is performed which often does not return expected results. It would be much better if this dropdown were driven by an advanced search.

![image](https://github.com/archesproject/arches-for-science/assets/1877663/d4388df4-fc32-4db3-81a8-769ef41a4ba3)

**Comment by chrabyrd** [comment]
cannot reproduce.
