### ISSUE TITLE
Show Object(s) of study rather than all objects in report intro

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-for-science-prj#1436]
This table should only show the Object selected in step 1

![Image](https://github.com/archesproject/arches-for-science/assets/1877663/b9a01050-6697-435f-97b3-38e8a7e9c15b)

**Comment by chiatt** [comment]
This table should only show the Object selected in step 1

![Image](https://github.com/archesproject/arches-for-science/assets/1877663/b9a01050-6697-435f-97b3-38e8a7e9c15b)

**Comment by jacobtylerwalls** [comment]
@njkim wondered if there was a chance this was intentional in https://github.com/archesproject/arches-for-science/pull/1271#discussion_r1353827524.

**Comment by chiatt** [comment]
The distinction between samples and analysis areas makes sense, but I believe only the objects of study should be listed in the first table. The samples are listed later in the report: 
![image](https://github.com/archesproject/arches-for-science/assets/1877663/e36ca711-64fa-4acf-875d-08d9af888785)
