### ISSUE TITLE
Failing chem analysis upload

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-for-science-prj#1448]
When uploading a chem analysis file in the Chem Analysis Data Upload workflow, the file appears to have uploaded, but the upload fails:

![image](https://github.com/archesproject/arches-for-science/assets/1877663/154183f2-5628-4217-a8af-879cd3e0a978)

In s3, the file also appears to have uploaded, but the size of the file (in this case 5MB) shows 0 bytes.
![image](https://github.com/archesproject/arches-for-science/assets/1877663/f7d622ff-c07a-4dda-b76c-a71fbe3ecb27)

**Comment by aarongundel** [comment]
This was due to misconfigured CORS permissions.  The PR for this request makes the failure more obvious and suggests examining CORS permissions.
