### ISSUE TITLE
Remove step information from workflows

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-for-science-prj#1456]
AFS will rely on the workflow/plugin help rather than the step information defined in each workflow. For this ticket we just need to remove the informationboxinfo from each step in each of the workflow files. eg: https://github.com/archesproject/arches-for-science/blob/b8ec57078aabf843214d1e539a4965e2e5c00f98/arches_for_science/media/js/views/components/plugins/sample-taking-workflow.js#L24-L27

**Comment by jacobtylerwalls** [comment]
Fixed in #1462
