### ISSUE TITLE
[VGM] how do I delete an image inside a manifest?

### ISSUE THREAD

**Issue by anamartinsvgm** [archesproject/arches-for-science-prj#1486]
We are exploring creating a gallery of images for a painting by uploading them via the image manager
If I try to delete an image from that gallery I see the delete button but get a message "Request Failed...
Sorry! The request failed. Please try again. Contact your system administrator if the problem persists."

![image](https://github.com/archesproject/arches-for-science/assets/125677450/bacbbae0-3164-401c-87a6-dde9c1f7d7d6)

**Comment by chiatt** [comment]
I'm not sure what happened here @anamartinsvgm. We'll look into it.

**Comment by aarongundel** [comment]
I was not able to reproduce this issue on the vgm test machine or locally - I was able to delete the image with an equally permissioned user.  I'd need more information to reproduce this issue.
