### ISSUE TITLE
Undoing a resource instance select updates in background but not in UI

### ISSUE THREAD

**Issue by jacobtylerwalls** [archesproject/arches-for-science-prj#1487]
Update Project Workflow (or X/Y instrument info step):
- Select a project
- Save and continue
- Exit
- Return to incomplete workflow
- See saved project value
- Use the "X" to clear it
- Click "Undo" (orange button)

Notice the widget doesn't change, but advancing forward and back shows the project from step 1 was restored.

**Comment by aarongundel** [comment]
Will be fixed with attached PR when https://github.com/archesproject/arches/issues/10505 is dealt with

**Comment by aarongundel** [comment]
Good for QA after arches#10505 is reviewed.
