### ISSUE TITLE
[VGM] how to delete a physical thing

### ISSUE THREAD

**Issue by anamartinsvgm** [archesproject/arches-for-science-prj#1489]
how do I delete a physical thing? (for now I have renamed them)
![image](https://github.com/archesproject/arches-for-science/assets/125677450/ac123858-8137-44ec-a264-d355fb30f80b)

**Comment by chiatt** [comment]
You have to click `edit` in the search result and then delete the resource in the editor: 
![image](https://github.com/archesproject/arches-for-science/assets/1877663/e3637feb-0d10-4440-bac6-bdc146d9fcd8)
