### ISSUE TITLE
Project report workflow isn't pulling in physical things

### ISSUE THREAD

**Issue by jacobtylerwalls** [archesproject/arches-for-science-prj#1497]
![Screenshot 2023-12-11 at 5 32 18 PM](https://github.com/archesproject/arches-for-science/assets/38668450/94574f0b-503f-4952-95a2-f2bc36aaea3a)

**Comment by chiatt** [comment]
@jacobtylerwalls, are you still seeing this bug? I haven't been able to reproduce it. Maybe it was caused by the accessibility work and has since been resolved.

**Comment by jacobtylerwalls** [comment]
I think it was just that my object didn't have any samples. Some workflows have a warning message about that above the object pickers, but this one doesn't seem to.
