### ISSUE TITLE
IIIF Services Digital Resources are not reindexed when after manifest changes

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-for-science-prj#1529]
To reproduce:

1. Create a manifest with a canvas
2. Notice that the primary descriptor for the digital resource is the name of the first uploaded canvas
3. Change the name of the manifest and save
4. Notice that the name of the digital resource instance has changed, but the indexed primary descriptor hasn't.

**Comment by jacobtylerwalls** [comment]
Is it fixed by #1513?

EDIT: no, it's not.

**Comment by chiatt** [comment]
> Is it fixed by #1513?
> 
> EDIT: no, it's not.

Thanks for checking @jacobtylerwalls
