### ISSUE TITLE
Missing Workflows UI problem (AfS dev/1.1.x, Arches dev/7.6.x)

### ISSUE THREAD

**Issue by ekansa** [archesproject/arches-for-science-prj#1555]
I seem to be missing the workflows under the heading "Upload 3-D Data Sets and Derivative Products":

![image](https://github.com/archesproject/arches-for-science/assets/1286742/9880eab3-0115-4b9d-b3f9-4a49d35954d9)

**Comment by chiatt** [comment]
This is because those workflows only are available if you have s3 configured. However, it is a problem that the header for those workflows appears at the bottom.

**Comment by chiatt** [comment]
Closing to address just the extra heading issue here:  https://github.com/archesproject/arches-for-science/issues/1547
