### ISSUE TITLE
Afs (dev/1.1.x, Arches 7.6.x) Sample Taking Workflow freezes on Image Service Selection

### ISSUE THREAD

**Issue by ekansa** [archesproject/arches-for-science-prj#1559]
I'm working on workflow documentation for AfS, and am trying to use the vgm.test instance workflows to understand the steps so I can explain them in the user guide.

I ran into a problem with the Sample Taking workflow. I'm getting lots of javascript errors in the console (see)

![afs-error-sample-taking-image-service-step-1](https://github.com/archesproject/arches-for-science/assets/1286742/612eb8b2-6d4b-413f-9aba-372b5cf67cbf)

After selecting my Image Service, I clicked "Save and Continue" to go to the next step in the workflow, and ran into a 500 server side error. This prevented me from continuing.

![afs-error-sample-taking-image-service-step-2](https://github.com/archesproject/arches-for-science/assets/1286742/ede35e9f-1cf8-4072-a333-40521473ba28)

(I blurred out the domain and some other identifying information in case there's anything sensitive).

**Comment by jacobtylerwalls** [comment]
Hi Eric -- can you confirm this was a new image service you created locally (not a remote one?) If so, that's currently not working, see #1466.

(And PS -- you can expand the errors in the console in order to paste them, better for search and no blurring required!)

**Comment by ekansa** [comment]
I tried to use an existing image service, but one defined (owned?) by a different project. I'll try to reproduce this again to give you better console errors that easier copy/pasta (noodles are better than paste)

**Comment by chiatt** [comment]
Thanks @ekansa, but I think I tracked it down. When we added creation of digital resources for canvases when using Cantaloupe, the behavior changed for remote (non-Cantaloupe) manifests. This certainly needs to be fixed, but if you test with a Cantaloupe service, I suspect it will work for you.

**Comment by chiatt** [comment]
Ah - I just noticed @jacobtylerwalls's comment. I definitely think #1466 is the issue.
