### ISSUE TITLE
Create summary report for the Collection/Set model

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-for-science-prj#203]
See page 4 of the mockup: https://www.dropbox.com/home/Arches4/Mockups?preview=Summary+Reports.pdf

**Comment by njkim** [comment]
To QA, you can run to register the report,
python manage.py report register --source afs/pkg/extensions/reports/collection_set/collection-set.json
and link the report in the card designer.

**Comment by chiatt** [comment]
Closing as changes to this feature will likely be needed due to graph/report changes.
