### ISSUE TITLE
Create summary report for the Group model

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-for-science-prj#204]
@chiatt commented on [Wed Jun 03 2020](https://github.com/archesproject/arches/issues/6254)

See page 6 of the mockups: https://www.dropbox.com/home/Arches4/Mockups?preview=Summary+Reports.pdf

**Comment by njkim** [comment]
To QA, you can run to register the report,
python manage.py report register --source afs/pkg/extensions/reports/group/group.json
and link the report in the card designer.

**Comment by chiatt** [comment]
Closing as changes to this feature will likely be needed due to graph/report changes.
