### ISSUE TITLE
File to IIIF Function: Need to provide user instruction

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches-for-science-prj#215]
A function is used to populate the IIIF manifest for a Physical Thing.  The function requires some  configuration from the model designer, but does not provide any guidance on what is being configured:

![Screen Shot 2020-07-07 at 11.06.00 AM.png](https://images.zenhubusercontent.com/56f1ad0a6caf56c9d38e1cbd/822d4c93-8acd-42f5-bbd2-45e4f8383829)

**Comment by chiatt** [comment]
Resolved in #269
