### ISSUE TITLE
Physical Thing Parts card is broken

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches-for-science-prj#216]
The card used to manage IIIF manifests in the Physical Thing Parts card is broken as show in the following screen capture.

Note the following:
1. When no visual work is assigned to the instance, the Parts card loads but does not show any manifests
2. When a visual work is assigned to the instance, the Parts card fails to load and throws an error

https://recordit.co/R3rSj0zg5y

**Comment by chiatt** [comment]
Working in lastest
