### ISSUE TITLE
Physical Thing Summary Report does not show associated manifest thumbnails

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches-for-science-prj#236]
If a physical thing includes a reference to a visual work, and the visual work includes a reference to a digital resource manifest, the Physical Thing report should show the thumbnails from the manifest.

This was working, but no long is.  Perhaps related to the updated r-i datatype?

**Comment by robgaston** [comment]
@dwuthrich this seems to be working for me, but only with newly created physical things.  I created a new physical thing via the workflow (new physical thing) and the manifest shows up in both the editor and in the "physical thing" summary report.  I checked the physical thing summary report in both the search page and in step 2 of the "create collection" workflow, and the manifest image showed up in both places.  Is it possible that this is a data issue? am I missing something?

**Comment by dwuthrich** [comment]
Yes, it works for me when I create a new Physical Thing via the workflow.  Can you suss out why the report isn't working for physical thing instances that are bulk loaded into AfS?

**Comment by robgaston** [comment]
@dwuthrich it appears that there are references in the buisness data to resource instances that do not exist in the database.  It is hard for me to say how the data got into this state...

**Comment by chiatt** [comment]
Closing because the relationship between physical things and digital resources has changed in the latest models.
