### ISSUE TITLE
AfS: Importing files breaks charting card

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches-for-science-prj#244]
The current import for AfS breaks the charting card used in Digital Resources:

![Screen Shot 2020-07-17 at 1.07.26 PM.png](https://images.zenhubusercontent.com/56f1ad0a6caf56c9d38e1cbd/ded822d1-e262-421f-8536-196b1421cddb)

**Comment by chiatt** [comment]
Closing because this issue will be resolved in archesproject/arches#6429
