### ISSUE TITLE
Activity Model Review

### ISSUE THREAD

**Issue by Habennin** [archesproject/arches-for-science-prj#258]
This issue is opened as part of a general fit-for-purpose review of the implemented models of the Arches for Science implementation. The goal of this review is to analyze the models from the user perspective in order to ascertain that they are:

a) functional (all fields working, e.g. dropdowns set, appropriate values available)
b) understandable (model, branch and field/node labels accessible and understandable to users)
c) adequate (user has sufficient fields to document the entity of interest in a manner which captures the features of interest in tracking that entity)

To support this review process, a google document to prepare shared group review commentary has been created here:

https://docs.google.com/document/d/1FFDTTK-a2p6NSawbE-qcpJA4uY71nS4Egq59ZVfro-8/edit?usp=sharing

The recommended review process is to test the model for adequacy through the direct testing of real data relevant to documentation of projects, research tasks and experiments in the proposed model. 

In addition to the above review document, the on-going draft documentation of the models are available here:

General: https://docs.google.com/document/d/1wfjjdm4GzghRzWm4hWWzJGJ8VfA5vGts2Yq-nD4Pu1s/edit#

Field by Field: https://docs.google.com/spreadsheets/d/141RjbDz6SPYH-PMJaVFypQACeS-x3hu1v_fPvn7m714/edit?usp=drive_web&ouid=115809866274616295104

This model review is scheduled to be discussed at the disco weekly meeting of Aug 4, 2020.

**Comment by chiatt** [comment]
Hey @Habennin & @annabelleee, is this review completed?

**Comment by chiatt** [comment]
Closing as there is no longer an 'Activity' Model.
