### ISSUE TITLE
IIIF Widget causes error in instance report

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches-for-science-prj#260]
After creating an annotation in the Visual Work model, Arches throws a KO error in the instance report.  See: https://recordit.co/TxvPtnq5TK

**Comment by chrabyrd** [comment]
Manually tested this behavior while testing https://github.com/archesproject/arches/pull/6577 . The KO error is no longer thrown and everything looks to be in working order. Closing for now! 🔧
