### ISSUE TITLE
Broken card in Visual Work instancec

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches-for-science-prj#261]
The Identifier Card in the Visual Work model does not show tiles properly:![Screen Shot 2020-08-24 at 9.38.04 AM.png](https://images.zenhubusercontent.com/56f1ad0a6caf56c9d38e1cbd/6df4e0ce-8ef2-4d98-afb1-3a44a6d828e8)

**Comment by chiatt** [comment]
Closing as this will be addressed in arches/archesproject#6570
