### ISSUE TITLE
IIIF Annotation Card in Physical Thing model is broken

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches-for-science-prj#262]
Trying to add an annotation to a Physical Thing instance using the Parts card throws an KO error and the card does not load: ![Screen Shot 2020-08-24 at 9.46.00 AM.png](https://images.zenhubusercontent.com/56f1ad0a6caf56c9d38e1cbd/fa046a47-68bb-4729-879d-f0c09ce7cde3)

**Comment by chiatt** [comment]
This will be addressed under: https://github.com/archesproject/arches/pull/6568 archesproject/arches#6567
