### ISSUE TITLE
KO Problem with statement card in AfS

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches-for-science-prj#264]
A cardinality n card does not render properly in AfS, as shown in attached image

![Screen Shot 2020-08-25 at 10.34.22 AM.png](https://images.zenhubusercontent.com/56f1ad0a6caf56c9d38e1cbd/7ec74955-c713-4878-938f-a15220e0669d)

**Comment by chiatt** [comment]
To be addressed under arches/archesproject#6570
