### ISSUE TITLE
In the 'Visual Work' resource model, new polygons created in the 'Polygon Identifier' card are not listed under the associated section in the resource instance header unless the 'Used Image' field is populated. 

### ISSUE THREAD

**Issue by chrabyrd** [archesproject/arches-for-science-prj#266]
In the 'Visual Work' resource model, new polygons created in the 'Polygon Identifier' card are not listed under the associated section in the resource instance header unless the 'Used Image' field is populated. 

To reproduce:
1. Navigate to the 'Add New Resource' view
2. Select 'Visual Work'
3. Add a manifest in the 'Polygon Identifier' card. ( example: https://media.ng-london.org.uk/iiif/000-03JR-0000/manifest.json )
4. Create a polygon in the same card
5. Leave the 'Used Image' field blank.
6. Navigate the to resource report ( top node of tree )
7. Click the 'Polygon Identifier' heading
8. Notice how the picture is not loaded.

NOTE: Filling out the 'Used Image' field yields somewhat better behavior. The image is visible, but in the dimensions of the 'Used Image'  image. 

UX seen here: https://recordit.co/NS4hwukPoO

**Comment by chiatt** [comment]
Closing because the Visual Work resource model will be deprecated in upcoming graph changes
