### ISSUE TITLE
Problem with display of card in designer when checklist option selected

### ISSUE THREAD

**Issue by Habennin** [archesproject/arches-for-science-prj#277]
There may be an issue in the card designer view that occurs when the node type is a concept collection and the widget for displying it is set to radio button. The preview section gets expanded to a very large dimension meaning that the right hand widget controlling toolbar is off screen and inaccessible. This disrupts the ability to work with the node henceforth. 

This seeming bug has been noticed in the A4S instance of the Getty. It can be witnessed on the type field of the project model. 

A screen shot below shows the issue. The screenshot is not cut off, one can only see that much of the desginer, the rest if off screen and inaccessible. Sorry if I tag the wrong person to look at it.

George

<img width="1451" alt="Screen Shot 2020-10-16 at 6 03 30 PM" src="https://user-images.githubusercontent.com/12068255/96275470-724f0300-0fda-11eb-9d43-ae727b324687.png">

**Comment by adamlodge** [comment]
+1 on this.  Identical issue to this: https://app.zenhub.com/workspaces/arches-56f071f2c4e4bfeb250fd249/issues/archesproject/arches/6725

**Comment by chiatt** [comment]
Thanks @Habennin, I'm going to close this ticket because it applies to core arches as well as AfS and is addressed by archesproject/arches#6725
