### ISSUE TITLE
Physical thing workflow report contains leaflet error

### ISSUE THREAD

**Issue by chrabyrd** [archesproject/arches-for-science-prj#301]
The physical thing workflow creates a report that has a leaflet error: `TypeError: Cannot read property 'y' of undefined`

To reproduce:
1. Progress through the `Physical Thing` workflow
2. Navigate to the `links` tab of the corresponding report
3. Notice the leaflet console error, and the UI wonkiness around the uploaded IIIF

**Comment by chiatt** [comment]
Closing because the Phys thing workflow no longer exists
