### ISSUE TITLE
Polish thematic report template

### ISSUE THREAD

**Issue by chrabyrd** [archesproject/arches-for-science-prj#349]
- Add arrow buttons around tab container in a viewport-width-bound container, with logic to enable/disable scroll behavior and button UI depending on available x-overflow
- Remove logic regarding `columnName`, to be replaced with card-based label. This behavior is to be added to the label_based_graph
- Refactor `thematic.js` to pull `ThematicReportTab` into it's own component.
- Add column-sort functionality

**Comment by chiatt** [comment]
Closing because we will not be using this report template
