### ISSUE TITLE
Extra dataset created when more files are uploaded

### ISSUE THREAD

**Issue by aarongundel** [archesproject/arches-for-science-prj#477]
An extra dataset appears to be created when there are more files uploaded than are actually used in the select-dataset-files step in the upload dataset workflow.  Found by @chiatt

**Comment by aarongundel** [comment]
@chiatt I have struggled to replicate this.  I created a thing with a single part, then in the upload dataset workflow I chose multiple files and selected only one for the resultant dataset.  I only see one dataset created - not multiple datasets.  Perhaps I'm missing a replication step?

**Comment by chiatt** [comment]
Thanks @aarongundel, I don't think you're missing anything. I'll close this for now.
