### ISSUE TITLE
Display IIIF annotations in report

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches-for-science-prj#52]
We need to determine how best to show IIIF annotations in the report.  We could perhaps just render our IIIF annotation widget in a non-editable state, or we might try to render thumbnails.

I guess my default approach would be to just render the widget, but we should be thoughtful here before we implement something.

**Comment by chiatt** [comment]
Issue moved to [archesproject/arches #5998](https://github.com/archesproject/arches/issues/5998) via [**ZenHub**](https://www.zenhub.com/)

**Comment by chiatt** [comment]
Issue moved to [archesproject/arches #5999](https://github.com/archesproject/arches/issues/5999) via [**ZenHub**](https://www.zenhub.com/)
