### ISSUE TITLE
Stub out the UI for the new charting widget

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-for-science-prj#6]
Contact @dwuthrich for the latest mockup before starting on this ticket.

![Screen Shot 2019-03-13 at 3.42.38 PM.png](https://images.zenhubusercontent.com/57d0a2a4e40e5714b16e73d7/5439dae8-7453-48fb-80cb-91945c392f4a)

**Comment by dwuthrich** [comment]
meets requirements
