### ISSUE TITLE
Add sample, sample location, and analysis area concept values to physical thing types

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-for-science-prj#648]
In workflows we need to distinguish between samples, sample locations, and analysis areas as different types of physical things. To make this possible, concept values are needed on the Physical Thing type node

**Comment by annabelleee** [comment]
I understand the sample and analysis area concepts, but I have a question about sample location. That really isn't a type of Physical Thing. A sample is the same thing as sample location. @Habennin, thoughts?

**Comment by chiatt** [comment]
Resolved in #655
