### ISSUE TITLE
Duplicate sample physical things may be saved if going through workflow multiple times.

### ISSUE THREAD

**Issue by njkim** [archesproject/arches-for-science-prj#730]
In the sample taking workflow's sample location step, if a user saved the motivation and description and then come back to the step the values do not saved. It is also possible that they are not stored in the tiles.

**Comment by njkim** [comment]
It turned out that if a user go through the sampling workflow twice with the same project and physical thing with the same image service, he may create duplicate samples. The sample motivation / description appears to be missing but it actually will be the duplicate 2nd sample if the user saves it.

**Comment by chiatt** [comment]
This issue will be fixed (and likely other potential bugs) with the resolution of #858
