### ISSUE TITLE
IIIF card: image does not display properly when user dismisses workbench panel

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches-for-science-prj#77]
The IIIF image does not refresh properly when a workbench side panel is dismissed.  User has to resize browser window for leaflet to display image properly: https://recordit.co/ruaHykxBqc

**Comment by robgaston** [comment]
Issue moved to [archesproject/arches #6080](https://github.com/archesproject/arches/issues/6080) via [**ZenHub**](https://www.zenhub.com/)
