### ISSUE TITLE
AfS Editor Report Template: Existence template to show/hide information correctly

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches-for-science-prj#774]
The existence template currently shows the production event names/statements/identifiers/timespans even when no data exists for these cards

To reproduce:
1. Create new Physical Thing
2. Create a new Production Event tile by adding information to the top card of the branch (but no child data)
3. View the Existence tab in the report and note the presence of data blocks with no information

Example
![Screen Shot 2021-11-03 at 3 12 37 PM](https://user-images.githubusercontent.com/815185/140200852-ef722cf2-60ba-4171-9529-52ba0435f0f7.png)
:

**Comment by aarongundel** [comment]
This should be fixed when https://github.com/archesproject/arches/issues/7616 is resolved - revisit after that to reevaluate.

**Comment by aarongundel** [comment]
After discussion with @chrabyrd we figured out how to get around this - there's still an issue - [arches #8089](https://github.com/archesproject/arches/issues/8089) that will make this easier, but it should be working now.
