### ISSUE TITLE
In the upload dataset workflow, a user should be able to choose a sample

### ISSUE THREAD

**Issue by njkim** [archesproject/arches-for-science-prj#813]
The issue:
If a user chooses the 2nd option (Data from the consumption of the sample or object) then chooses one of the samples, "The selected physical thing is invalid" message appears.

The desired behavior:
Since the 2nd option assume the consumption of the sample, the user should be able to choose the sample. But probably only the sample not the analysis area or sample area.

**Comment by chiatt** [comment]
resolved in #820
