### ISSUE TITLE
File Viewer card does not support upload of .tiff images

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches-for-science-prj#88]
Card throws an error when attempting to upload and display .tiff files

**Comment by chiatt** [comment]
@dwuthrich It seems that the problem is that Chrome and Firefox no longer support tiff files: https://github.com/openseadragon/openseadragon/issues/1380

I think we might need to modify the file-list datatype to convert tiff files to a different image format so that it can be displayed.

**Comment by dwuthrich** [comment]
@chiatt We should assume that .tiff files will be uploaded to a IIIF server and processed for presentation to a browser.  I'm going to move this ticket to sprint staging until we're ready to tackle the IIIF upload support

**Comment by dwuthrich** [comment]
meets requirements
