### ISSUE TITLE
error installation: components id 10ae2f00-cbda-4a0d-8ca2-5af3b46b37ad  and Function matching query does not exist

### ISSUE THREAD

**Issue by enzococca** [archesproject/arches-for-science-prj#906]
Hello, I’m trying to install arches for science on arches 6.0.1 and I have this error:

afs/pkg/graphs/resource_models/Digital Resources.json
2022-04-12 10:08:22,779 arches.app.utils.data_management.resource_graphs.importer ERROR Function matching query does not exist.
Traceback (most recent call last):
File “/home/enzo/.local/lib/python3.8/site-packages/arches/app/utils/data_management/resource_graphs/importer.py”, line 86, in import_graph
graph = Graph(resource)
File “/home/enzo/.local/lib/python3.8/site-packages/arches/app/models/graph.py”, line 106, in init
default_config = models.Function.objects.get(functionid=function[“function_id”]).defaultconfig
File “/home/enzo/.local/lib/python3.8/site-packages/django/db/models/manager.py”, line 82, in manager_method
return getattr(self.get_queryset(), name)(*args, **kwargs)
File “/home/enzo/.local/lib/python3.8/site-packages/django/db/models/query.py”, line 406, in get
raise self.model.DoesNotExist(
arches.app.models.models.Function.DoesNotExist: Function matching query does not exist.
afs/pkg/graphs/resource_models/Visual Work.json
2022-04-12 10:08:23,212 arches.app.utils.data_management.resource_graphs.importer ERROR Function matching query does not exist.
Traceback (most recent call last):
File “/home/enzo/.local/lib/python3.8/site-packages/arches/app/utils/data_management/resource_graphs/importer.py”, line 86, in import_graph
graph = Graph(resource)
File “/home/enzo/.local/lib/python3.8/site-packages/arches/app/models/graph.py”, line 106, in init
default_config = models.Function.objects.get(functionid=function[“function_id”]).defaultconfig
File “/home/enzo/.local/lib/python3.8/site-packages/django/db/models/manager.py”, line 82, in manager_method
return getattr(self.get_queryset(), name)(*args, **kwargs)
File “/home/enzo/.local/lib/python3.8/site-packages/django/db/models/query.py”, line 406, in get
raise self.model.DoesNotExist(
arches.app.models.models.Function.DoesNotExist: Function matching query does not exist.
afs/pkg/graphs/resource_models/Observation.json
afs/pkg/graphs/resource_models/Sampling Activity.json
Traceback (most recent call last):
File “/home/enzo/.local/lib/python3.8/site-packages/django/db/backends/base/base.py”, line 240, in _commit
return self.connection.commit()
psycopg2.errors.ForeignKeyViolation: insert or update on table “cards” violates foreign key constraint “cards_componentid_63e855fd_fk_card_components_componentid”
DETAIL: Key (componentid)=(10ae2f00-cbda-4a0d-8ca2-5af3b46b37ad) is not present in table “card_components”.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File “manage.py”, line 30, in
execute_from_command_line(sys.argv)
File “/home/enzo/.local/lib/python3.8/site-packages/django/core/management/init.py”, line 381, in execute_from_command_line
utility.execute()
File “/home/enzo/.local/lib/python3.8/site-packages/django/core/management/init.py”, line 375, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File “/home/enzo/.local/lib/python3.8/site-packages/django/core/management/base.py”, line 323, in run_from_argv
self.execute(*args, **cmd_options)
File “/home/enzo/.local/lib/python3.8/site-packages/django/core/management/base.py”, line 364, in execute
output = self.handle(*args, **options)
File “/home/enzo/.local/lib/python3.8/site-packages/arches/management/commands/packages.py”, line 341, in handle
self.load_package(
File “/home/enzo/.local/lib/python3.8/site-packages/arches/management/commands/packages.py”, line 925, in load_package
load_graphs(package_location)
File “/home/enzo/.local/lib/python3.8/site-packages/arches/management/commands/packages.py”, line 634, in load_graphs
self.import_graphs(resource_models, overwrite_graphs=overwrite_graphs)
File “/home/enzo/.local/lib/python3.8/site-packages/arches/management/commands/packages.py”, line 1204, in import_graphs
errs, importer = ResourceGraphImporter(archesfile[“graph”], overwrite_graphs)
File “/home/enzo/.local/lib/python3.8/site-packages/arches/app/utils/data_management/resource_graphs/importer.py”, line 143, in import_graph
return errors, reporter
File “/home/enzo/.local/lib/python3.8/site-packages/django/db/transaction.py”, line 240, in exit
connection.commit()
File “/home/enzo/.local/lib/python3.8/site-packages/django/db/backends/base/base.py”, line 262, in commit
self._commit()
File “/home/enzo/.local/lib/python3.8/site-packages/django/db/backends/base/base.py”, line 240, in _commit
return self.connection.commit()
File “/home/enzo/.local/lib/python3.8/site-packages/django/db/utils.py”, line 89, in exit
raise dj_exc_value.with_traceback(traceback) from exc_value
File “/home/enzo/.local/lib/python3.8/site-packages/django/db/backends/base/base.py”, line 240, in _commit
return self.connection.commit()
django.db.utils.IntegrityError: insert or update on table “cards” violates foreign key constraint “cards_componentid_63e855fd_fk_card_components_componentid”
DETAIL: Key (componentid)=(10ae2f00-cbda-4a0d-8ca2-5af3b46b37ad) is not present in table “card_components”.

so the key component id 10ae2f00-cbda-4a0d-8ca2-5af3b46b37ad is not present and some python error where function matching query doesn’t exist.

about the key components I fellow this discussion [Arches For Science vs Arches](https://community.archesproject.org/t/arches-for-science-vs-arches/1548) but I can’t fix it.

How can install arches for science?

Best
E

**Comment by chiatt** [comment]
@enzococca I'm assuming you got AfS working given your question on the forum [here](https://community.archesproject.org/t/arches-for-science-this-project-has-no-associated-objects-your-project-must-have-an-associated-object-collection-with-an-object-before-proceeding/1576?u=cyrus)
