### ISSUE TITLE
This project has no associated Objects. Your project must have an associated Object Collection with an Object before proceeding.

### ISSUE THREAD

**Issue by enzococca** [archesproject/arches-for-science-prj#907]
Hello, 
After I created a project, collection and object I'm trying to use analysis area or upload a dataset, but when I try to insert the proj I created it say 

"This project has no associated Objects. Your project must have an associated Object Collection with an Object before proceeding".

So where wrong I? I miss something?

Best
E

**Comment by chiatt** [comment]
Closing to keep this discussion on the forum [here](https://community.archesproject.org/t/arches-for-science-this-project-has-no-associated-objects-your-project-must-have-an-associated-object-collection-with-an-object-before-proceeding/1576?u=cyrus).
