### ISSUE TITLE
Related resources tab is broken

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches-for-science-prj#909]
The related resources tab in the AfS search interface is broken and fails with a JS error as shown in the following image:

![Screen Shot 2022-05-11 at 10.43.43 AM.png](https://images.zenhubusercontent.com/56f1ad0a6caf56c9d38e1cbd/2373883a-47dd-451c-be4c-05ee644104f5)

**Comment by chiatt** [comment]
I think we noticed this about the same time yesterday @dwuthrich. It should be working now that this PR is merged archesproject/arches#8416
