### ISSUE TITLE
Identify best method for uploading very large files

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-for-science-prj#910]
Uploading very large files ~10GB is an AFS requirement. We need to identify way(s) to best support that requirement.

**Comment by aarongundel** [comment]
Note that PR. https://github.com/archesproject/arches/pull/8713 is required for this to work.

**Comment by aarongundel** [comment]
on hold until after 0.9.x release

**Comment by chiatt** [comment]
We have opted for 'Uppy'
