### ISSUE TITLE
RelatedObjectDoesNotExist and TileValidationError

### ISSUE THREAD

**Issue by fatmaaladag1** [archesproject/arches-for-science-prj#916]
Dear All,
In our Arches project, we use the Heritage Asset section and made data entries to certain modules. However, we cannot update any previously entered data. If we enter a new data in the Heritage Asset, all sections work very well. The problem is that we cannot edit a data that we entered before. It gives the following errors: RelatedObjectDoesNotExist and TileValidationError... Does anyone have any ideas?

**Comment by chiatt** [comment]
This discussion is continued on the forum here: https://community.archesproject.org/t/relatedobjectdoesnotexist-and-tilevalidationerror/1619
