### ISSUE TITLE
Physical Thing report changes

### ISSUE THREAD

**Issue by aarongundel** [archesproject/arches-for-science-prj#932]
The physical thing model's report needs to be modified.  

### Overall Tab Changes
- Change “names and classifications” to “Names, identifiers, classification”
- Move “descriptions” to second position
- Change ‘Substance’ to ‘physical description’
- Change “actor relations” to “provenance”
- Change existence to “key events”
- Change “aboutness” to “content and iconography”
- Change “parthood” to “components” – we want distinction between parents/children 
- Change “sethood” to “related collection and sets”

### Description Tab Changes
- Ensure that the note, descriptions statement types are on this tab 
- Add ‘credit line’ statement to this tab

### Provenance Tab Changes
- Add provenance statement to this tab

### Physical Description Tab Changes
- Add materials/media statement type to the data on this tab
- Includes dimension statement type

**Comment by chiatt** [comment]
Completed in #970
