### ISSUE TITLE
Observation Report changes

### ISSUE THREAD

**Issue by aarongundel** [archesproject/arches-for-science-prj#936]
### Overall tab changes
- Change “names and classifications” to “Names, identifiers, classification”
- Move “descriptions” to second position
- Add a "related objects" tab
- Add a "data" tab
- Change “substance” to “dates”
- Remove “location” tab
- Change “parthood” to “parent project”

### Descriptions tab changes
- Move contents of ”parameters and outcomes” to this tab EXCEPT “recorded value of observation” - see below

### Related Objects tab
- Table with all physical things related resources
-  ~Include the ‘spot map’ here – annotated image w/ with the regions of interest noted like it appears on the summary page of the ‘analysis areas’ workflow~ - moved to https://github.com/archesproject/arches-for-science-prj/issues/1000

### Data tab
- “recorded value of observation” goes here

**Comment by johnatawnclementawn** [comment]
Claimed

**Comment by johnatawnclementawn** [comment]
Claimed
