### ISSUE TITLE
Installation instructions in readme.txt

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches-for-science-prj#94]
The generic installation instructions from the referenced page in the readme file don't work for the package, at least in the current state.

In particular:
- [ ] Need to run `python ./manage.py setup_db`, not packages -o setup_db
- [ ] missing `media/img/landing/museum_at_night.jpg`, I copied a random-ish image there
- [ ] no instructions for how to load the models, for /this/ package. I did: `python ./manage.py packages -o load_package -s afs/pkg/`
- [ ] `cd afs ; rm yarn.lock ; yarn install --network-timeout 1000000`

**Comment by chiatt** [comment]
Issue moved to [archesproject/arches-docs #207](https://github.com/archesproject/arches-docs/issues/207) via [**ZenHub**](https://www.zenhub.com/)
