### ISSUE TITLE
Zoom problems in Manifest Manager

### ISSUE THREAD

**Issue by aarongundel** [archesproject/arches-for-science-prj#944]
The zoom control is wonky in the manifest manager when doing an image comparison.  

1. Open manifest manager with two images.  
2. Select two images for comparison. 
3. Try to zoom in and out.  Sometimes the zoom in and out controls will disable at the same time.  

This may have to do with the different sizes of both images and may end up needing to be fixed in the image comparison library.

**Comment by aarongundel** [comment]
This may actually be tied to small images (less than 300x300px) as well; some additional testing may be required.

**Comment by njkim** [comment]
What appears to happen is that it looks like the zoom is not functioning any more when one of the images cannot be zoomed in any further due to the small original size.

**Comment by chiatt** [comment]
It makes sense that this issue arises with small files. There isn't enough data for Cantaloupe to cut tiles at different zoom levels. I think most files used in AfS will be pretty large, so it shouldn't be a problem.
