### ISSUE TITLE
Cannot refresh regions step in Analysis Areas Workflow

### ISSUE THREAD

**Issue by aarongundel** [archesproject/arches-for-science-prj#946]
There is a problem when using the analysis areas workflow and refreshing the regions step after entering a new analysis area.

1. Go through the Analysis areas workflows to the regions step.
2. Create a new Analysis Area
3. Create a new Analysis Area - you should see that the workflow will allow you to move forward.
4. Refresh the page. Note that the analysis area is gone, but the workflow still allows you to move forward.  The analysis area still appears to exist, although it is no longer visible.  
5. Try to add a new analysis area. You're no longer able to save a new analysis area.

**Comment by njkim** [comment]
This may be caused by https://github.com/archesproject/arches/issues/8935

**Comment by aarongundel** [comment]
confirmed fixed.
