### ISSUE TITLE
Allow new instrument creation in the Upload Dataset workflow

### ISSUE THREAD

**Issue by aarongundel** [archesproject/arches-for-science-prj#947]
Currently, you cannot add a new instrument in the Upload Dataset workflow (Observation Info Step) - you must exit the workflow and/or open a new tab to enter the instrument information and then refresh the page.  It would be better if this worked like the "Procedure Used" - allowing you to enter a new procedure if there isn't one already.

**Comment by chiatt** [comment]
I don't think we want to allow users to do this. This would allow the user to create an instrument that the second half of the workflow will not know how to interpret. Granted, a user could create a new instrument in the resource editor, but it should not be so easy as to be able to do it in the workflow.
