### ISSUE TITLE
Free floating checkbox in review dataset workflow

### ISSUE THREAD

**Issue by aarongundel** [archesproject/arches-for-science-prj#949]
It appears that the related dataset workflow can produce a list of related resources with checkboxes (not sure why; not seeing any instructions on what these checkboxes actually do).  It's also possible for the displayname for these related resources to be undefined, producing strange free floating checkboxes without context after you select a physical thing.  

![Screen Shot 2022-09-01 at 10 30 41 AM](https://user-images.githubusercontent.com/124614/187966506-a604dc9e-e151-4a79-a4f9-56b21216094f.png)

At minimum, we should ensure that the display name exists before we show a checkbox.  It would also be good to provide some instructions on why a user is selecting these related resources.

**Comment by njkim** [comment]
No checkbox appears for me.
@aarongundel Is there a certain condition that the checkbox shows up or does it always appear?

**Comment by apeters** [comment]
@aarongundel  I don't observe this behaviour either.

**Comment by aarongundel** [comment]
I'm not seeing this anymore either.  Likely resolved by a dataset load and/or modifications in other tickets.  Closing as complete.
